### ISSUE TITLE
UUID Package renamed to elixir_uuid

### ISSUE THREAD

**Issue by DiaanEngelbrecht** [membraneframework/webrtc-server#6]
Looks like the uuid package was renamed to elixir_uuid. This causes dependency conflicts on any project using the new elixir_uuid package. See the below issues for reference.

[Some context to why they did it.](https://elixirforum.com/t/setting-path-to-deps-for-elixir-uuid-and-erlang-uuid/14333/10)

[The uuid package issue related to this.](https://github.com/zyro/elixir-uuid/issues/24)

[Related issue on a different project](https://github.com/getsentry/sentry-elixir/issues/294)

Fix should be simple, I'll bump the dependency and submit a PR if the tests pass.

**Comment by DiaanEngelbrecht** [comment]
Seems like I can't push my branch. Updated mix.exs to:

`
defp deps do
    [
      {:elixir_uuid, "~> 1.2"},
      {:cowboy, "2.8.0"},
      {:jason, "1.2.2"},
      {:dialyxir, "1.0.0", only: [:dev], runtime: false},
      {:credo, "1.5.4", only: [:dev, :test], runtime: false},
      {:bimap, "1.1.0"},
      {:ex_doc, "0.23.0", only: :dev, runtime: false},
      {:bunch, "1.3.0"}
    ]
  end
`

All tests passed.

**Comment by mickel8** [comment]
Hi @DiaanEngelbrecht,
thanks for the catch. I have created PR with changes. We will probably merge and relese it on Monday :wink:
